"""2_social accounts

Revision ID: 08b163472817
Revises: fc625d8c0da8
Create Date: 2023-07-10 13:25:39.464434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b163472817'
down_revision = 'fc625d8c0da8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_account',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('social_name', sa.String(length=20), nullable=True),
    sa.Column('social_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.UniqueConstraint('user_id', 'social_id', name='unique_user_id_social_id')
    )
    op.create_index(op.f('ix_social_account_id'), 'social_account', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_account_id'), table_name='social_account')
    op.drop_table('social_account')
    # ### end Alembic commands ###
