version: "3.9"

services:
  postgres_auth:
    env_file:
      - .envs/.prod/.postgres

  redis_auth:
    env_file:
      - .envs/.prod/.redis

  api_auth:
    build:
      args:
        - BUILD_ENV=prod
    command: /start_prod
    env_file:
      - .envs/.prod/.postgres
      - .envs/.prod/.api
      - .envs/.prod/.redis

  nginx:
    restart: always
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "80:80"
    env_file:
      - .envs/.prod/.api
    depends_on:
      - api_auth
    networks:
      - local_network_auth

  jaeger_auth:
    ports:
      - "6831:6831/udp"
      - "16686:16686"