version: "3.9"

services:
  postgres_auth:
    restart: always
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    container_name: postgres_auth
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/staticfiles/backups
    networks:
      - local_network_auth
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 3s
      timeout: 10s
      retries: 3

  redis_auth:
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    container_name: redis_auth
    networks:
      - local_network_auth
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping", "|", "grep", "PONG" ]
      interval: 3s
      timeout: 10s
      retries: 3

  api_auth:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: api_auth
    volumes:
      - local_postgres_data_backups:/app/staticfiles/backups
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - .:/app
    expose:
      - "8080"
    depends_on:
      postgres_auth:
        condition: service_healthy
      redis_auth:
        condition: service_healthy
    networks:
      - local_network_auth
    healthcheck:
      test: [ "CMD-SHELL", "curl -H 'X-Request-Id: healthcheck' --fail -f http://$$API_AUTH_HOST:$$API_AUTH_PORT/docs" ]
      interval: 3s
      timeout: 10s
      retries: 3

  nginx_auth:
    restart: always
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx_auth
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - api_auth
    networks:
      - local_network_auth
      - shared_network
    healthcheck:
      test: ["CMD", "nc", "-z", "nginx_auth", "81"]
      interval: 3s
      timeout: 10s
      retries: 3

  jaeger_auth:
    build:
      context: .
      dockerfile: ./docker/jaeger/Dockerfile
    container_name: jaeger_auth
    restart: always
    healthcheck:
      test: [ "CMD", "nc", "-z", "jaeger_auth", "16686" ]
      interval: 3s
      timeout: 10s
      retries: 3

networks:
  local_network_auth:
    driver: bridge
  shared_network:
    external: true

volumes:
  local_postgres_data: { }
  local_postgres_data_backups: { }
  local_elastic_search_data: { }
  static_volume:
  media_volume:
