"""2_social

Revision ID: 69bd396dfbc9
Revises: fc625d8c0da8
Create Date: 2023-06-25 21:20:03.297628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69bd396dfbc9'
down_revision = 'fc625d8c0da8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('social_id_google', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('social_id_yandex', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('social_id_vk', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'social_id_vk')
    op.drop_column('user', 'social_id_yandex')
    op.drop_column('user', 'social_id_google')
    # ### end Alembic commands ###
